version: '3.8'
services:
  db:
    image: postgres:16.1-bookworm
    container_name: todo-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=todo_list
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - todo-list-data:/var/lib/postgresql/data

volumes:
  todo-list-data:
