version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:21.0.0

      - image: cimg/postgres:16.1
        environment:
          - POSTGRES_DB=todo_list
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
    
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle" }}v
      - run:
          name: "Grant execute permission to Gradlew"
          command: "chmod +x ./gradlew"
      - run:
          name: Build
          command: "./gradlew clean build"
      - save_cache:
          key: gradle-{{ checksum "build.gradle" }}
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper

workflows:
  build-workflow:
    jobs:
      - build
