version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:21.0.0

      - image: cimg/postgres:16.1
        environment:
          - POSTGRES_DB=todo_list
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        volumes:
        - ./docker/postgres/init/01_init.sql:/docker-entrypoint-initdb.d/01_init.sql
    
    steps:
      - checkout
      - run:
          name: "Grant execute permission to Gradlew"
          command: "chmod +x ./gradlew"
      - run:
          name: Build
          command: "./gradlew clean build"

workflows:
  build-workflow:
    jobs:
      - build
